parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $emailBottleInventoryUserService: '%env(SERVICE_ACCOUNT_BOTTLE_INVENTORY_LOGIN)%'
            $passwordBottleInventoryUserService: '%env(SERVICE_ACCOUNT_BOTTLE_INVENTORY_PASSWORD)%'

    EmpireDesAmis\BottleInventory\:
        resource: '../src/'

    EmpireDesAmis\BottleInventory\DataFixtures\:
        resource: '../fixtures'

    EmpireDesAmis\BottleInventory\Application\EventListener\OnBottleTasted:
        tags: [ kernel.event_listener ]

    EmpireDesAmis\BottleInventory\Infrastructure\Country\Repository\CountryRepositoryInterface:
        alias: EmpireDesAmis\BottleInventory\Infrastructure\Country\Repository\CountryRepository

    EmpireDesAmis\BottleInventory\Infrastructure\User\Repository\UserRepositoryInterface:
        alias: EmpireDesAmis\BottleInventory\Infrastructure\User\Repository\UserRepository

    EmpireDesAmis\BottleInventory\Domain\Service\UploadBottlePictureInterface:
        alias: EmpireDesAmis\BottleInventory\Infrastructure\VichUploader\UploadBottlePictureVichUploader

    EmpireDesAmis\BottleInventory\Application\Adapter\BottleListAdapterInterface:
        alias: EmpireDesAmis\BottleInventory\Infrastructure\Doctrine\Adapter\BottleListDoctrineAdapter
        public: true

    EmpireDesAmis\BottleInventory\Application\Projection\CreateBottleProjection:
        tags: [ kernel.event_listener ]

    EmpireDesAmis\BottleInventory\Application\Projection\CreateBottleListProjection:
        tags: [ kernel.event_listener ]

    EmpireDesAmis\BottleInventory\Application\Projection\AddPictureBottleProjection:
        tags: [ kernel.event_listener ]

    EmpireDesAmis\BottleInventory\Application\Projection\AddPictureBottleListProjection:
        tags: [ kernel.event_listener ]

    EmpireDesAmis\BottleInventory\Application\Projection\TasteBottleProjection:
        tags: [ kernel.event_listener ]

    EmpireDesAmis\BottleInventory\Application\Projection\UpdateBottleProjection:
        tags: [ kernel.event_listener ]

    EmpireDesAmis\BottleInventory\Application\Projection\UpdateBottleListProjection:
        tags: [ kernel.event_listener ]

    EmpireDesAmis\BottleInventory\Application\Projection\DeleteBottleProjection:
        tags: [ kernel.event_listener ]

    EmpireDesAmis\BottleInventory\Application\Projection\DeleteBottleListProjection:
        tags: [ kernel.event_listener ]

when@dev:
    services:
        EmpireDesAmis\SecurityAuthenticatorBundle\Firebase\Security\Authenticator\AuthenticateUserFromProviderFirebaseInterface:
            alias: EmpireDesAmis\SecurityAuthenticatorBundle\Firebase\Security\Authenticator\AuthenticateUserFromProviderFakeFirebase

when@test:
    services:
        EmpireDesAmis\BottleInventory\Infrastructure\Country\Repository\CountryRepositoryInterface:
            alias: EmpireDesAmis\BottleInventory\Infrastructure\Country\Repository\CountryFakeRepository
        
        EmpireDesAmis\BottleInventory\Infrastructure\User\Repository\UserRepositoryInterface:
            alias: EmpireDesAmis\BottleInventory\Infrastructure\User\Repository\UserFakeRepository
        
        EmpireDesAmis\BottleInventory\Domain\Service\UploadBottlePictureInterface:
            alias: EmpireDesAmis\BottleInventory\Infrastructure\VichUploader\UploadBottlePictureVichUploaderFake

        EmpireDesAmis\SecurityAuthenticatorBundle\Firebase\Security\Authenticator\AuthenticateUserFromProviderFirebaseInterface:
            alias: EmpireDesAmis\SecurityAuthenticatorBundle\Firebase\Security\Authenticator\AuthenticateUserFromProviderFakeFirebase